apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyvaluetimestamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keyvaluetimestamp
  template:
    metadata:
      labels:
        app: keyvaluetimestamp
    spec:
      containers:
        - name: keyvaluetimestamp
          image: martinlykke/keyvaluetimestamp:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: keyvaluetimestamp
spec:
  selector:
    app: keyvaluetimestamp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
